### ISSUE TITLE
Is it possible to dispatch log entries asynchronously / fire and forget?

### ISSUE THREAD

**Issue by holtkamp** [maxbanton/cwh#25]
I am currently researching whether it is possible to asynchronously send over log entries as a "send and forget" approach. The rationale of this is that during profiling with [Blackfire.io](https://blackfire.io), it turned out that currently dispatching the logs (and waiting for the response) takes around 25% of the time of a complete request cycle. Instead of reducing / disabling dispatching log entries, I thought maybe use a fire and forget approach... and just hope the entries arrive at Amazon🤞 .

Realizing this seems to be possible by using CurlMultiHandler as HTTP Handler of the CloudWatchLogClient and manually invoking the `tick()` as described here:

https://github.com/aws/aws-sdk-php/issues/621#issuecomment-111232418

In that case instead of `$this->client->putLogEvents($data);`, we should invoke `$this->client->putLogEventsAsync($data);`

@maxbanton have you already considered this? 

Whether this is completely possible is still something which seems debatable when looking at
https://github.com/guzzle/guzzle/issues/1127
https://github.com/guzzle/guzzle/issues/1425
https://github.com/guzzle/guzzle/issues/1429#issuecomment-197152914

I already tried to do this for the AwsCloudWatch client when sending over metrics. But it seems the request is still being "blocked". That might be covered by https://github.com/guzzle/guzzle/pull/1924/files

Another, 'simpler' way might be to set the response timeout really low: https://github.com/guzzle/guzzle/issues/1429#issuecomment-304449743

**Comment by maxbanton** [comment]
Hi, @holtkamp! 
Already looked to async SDK calls, but did not figured out how to implement truly asynchronous logs processing, because every call to AWS should be signed with `sequenceToken` which is returned on previous request.
Anyway, will look on it, thanks for the hints.

Kind regards, 
Max.

**Comment by maxbanton** [comment]
Hi, @holtkamp!
I did some research on topic and found that currently it's impossible to implement async behavior for logging, because every `putLogEvents` [should be signed](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html) with `nextSequenceToken` which changes on each request and can be obtained from previous call or from `describeLogStreams` call. 
Perhaps some changes will be made on the AWS API and `nextSequenceToken` will not be needed anymore, then we will be able to implement it.

Anyway, feed free to create a PR if you will find a way how to do it.

Regards,
Max.

**Comment by jdrydn** [comment]
Similar to @holtkamp, simply adding the `CloudwatchHandler` noticeably increased response times for my API, likely due to the increased latency of fetching the `nextSequenceToken` & sending the logs.

> Perhaps some changes will be made on the AWS API and nextSequenceToken will not be needed anymore, then we will be able to implement it.

Realistically, that's not going to happen anytime soon 🤷‍♂️ Therefore I sought another solution. For any interested, "solutions" I ruled out include:

- [`SqsHandler`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/SqsHandler.php) to a Lambda function to Cloudwatch.
- Adding [`FluentHandler `](https://github.com/nrk/monolog-fluent) to send logs to a `fluentd` instance which will buffer and batch-send logs to Cloudwatch (and to any other additional sources you may (not) have plans for).

The solution I'm settling on is wrapping this library with [`BufferHandler `](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/BufferHandler.php), calling [`fastcgi_finish_request`](http://php.net/manual/en/function.fastcgi-finish-request.php) after the response has been sent to the client, then calling `close()` to send messages to Cloudwatch.

The benefits here mostly include being able to skip the `BufferHandler` if executing a cron-job and directly send to Cloudwatch just by manipulating my init code. Yay!

**Note:** This only works because in this particular instance I have Nginx passing requests to PHP-FPM via FastCGI, which gives me `fastcgi_finish_request`. If this wasn't the case I'd likely be using a `fluentd` instance as I have confidence in it's ability to buffer varying amounts of load. Yay fluent!

**Comment by holtkamp** [comment]
@jdrydn, nice solution!

>then calling close() to send messages to Cloudwatch.

Since the LoggerHandlers would automatically close() upon shutdown / destruction, this would be an optional step for a "normal" incoming web request right? Or is it required to explicitly close all handlers "manually"?

**Comment by jdrydn** [comment]
>  this would be an optional step for a "normal" incoming web request right

Fair point @holtkamp, explicitly calling `close()` would be optional. I guess I'd do myself to be absolutely clear: `This is when my application sends data to Cloudwatch`, as opposed to letting the script "automagically" work.

**Comment by holtkamp** [comment]
https://github.com/maxbanton/cwh/issues/25#issuecomment-359414266, indeed, totally agree, just wanted to be sure I understood the mechanism. Thanks!

**Comment by holtkamp** [comment]
@maxbanton regarding your comment https://github.com/maxbanton/cwh/issues/25#issuecomment-349648743

The docs at https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html now state:

> The sequence token is now ignored in PutLogEvents actions. PutLogEvents actions are always accepted and never return InvalidSequenceTokenException or DataAlreadyAcceptedException even if the sequence token is not valid. You can use parallel PutLogEvents actions on the same log stream.


So that might offer possibilities...?

Update: note this is implemented in this fork https://github.com/phpnexus/cwh/releases/tag/v3.1.0
