### ISSUE TITLE
Exception on event size limit

### ISSUE THREAD

**Issue by jg42** [maxbanton/cwh#31]
Hello,

I allow myself to open a new issue regarding the size of the event "Amazon CloudWatch Logs".
Indeed, the limit is 256kb and if the limit is exceeded, AWS returns a "400 Bad Request". Following this, the execution interrupted. The exact answer is:
`{"__type":"InvalidParameterException","message":"Log event too large: xxxxxx bytes exceeds limit of 262144"}`

So I propose to just catch the exception in the "send" method:
`

    private function send(array $entries)
    {
        try{
            if (false === $this->initialized) {
                $this->initialize();
            }

            $data = [
                'logGroupName' => $this->group,
                'logStreamName' => $this->stream,
                'logEvents' => $entries
            ];

            if (!empty($this->sequenceToken)) {
                $data['sequenceToken'] = $this->sequenceToken;
            }

            $response = $this->client->putLogEvents($data);

            $this->sequenceToken = $response->get('nextSequenceToken');

        } catch (\Exception $ex){}
    }
`

What do you think?

**Comment by PhlebasThePhoenician** [comment]
Hi

came across the same issue. Altough going over the limit most likely means that something is done wrong, it's still bit undesirable to get PHP fatal from this.
Came up with attached changes, that worked for me, but propably not the ideal solution.
Some things left to improve:
- make event-size configurable, up to the max, by user, so you can control logsizes / splitting in more detail
- prefix/postfix texts configurable
- some ID for splitted lines to match them (did not have need for this for now)
- Or as proposed above, just catch the execption and fail the call silently

proposed patch:
[eventsize.patch.txt](https://github.com/maxbanton/cwh/files/1758260/eventsize.patch.txt)

(did not do PR yet, since this is very preliminary)

**Comment by PhlebasThePhoenician** [comment]
Hi,

small update, due to issues with logging directly from application to CloudWatch , i'v switched to use AWS ECS task-logging rules and just output everything to stdout/stderr from application, and (at least for now) will not do much for this

**Comment by maxbanton** [comment]
Hi @jg42. I don't know how you reached 256k per log limitation, I tried to reproduce and no luck.
You can try to optimize objects size that you are passing through log context.

Regards, Max.
