### ISSUE TITLE
Question: is it possibile to print full error stack?

### ISSUE THREAD

**Issue by falloppa** [maxbanton/cwh#60]
Good afternoon,
first of all i'd like to thank you for this useful package. After reading Laravel, Monolog and this package documentation i'm a little bit confused about the error printed in logs. It seems like i have in my logs only the first entry of Monolog error stack, but most of the time in Laravel it would be useful to have the full error stack printed. Is there a way to accomplish this?

**Comment by kryp7ik** [comment]
So I found this first because I was looking to do the same thing and after doing some searching I found the following solution that works nicely...
[https://stackoverflow.com/questions/20657309/logging-full-stack-trace-with-monolog](https://stackoverflow.com/questions/20657309/logging-full-stack-trace-with-monolog)

**Comment by maxbanton** [comment]
Hi @falloppa. Does solution by @kryp7ik works for you?

**Comment by falloppa** [comment]
@maxbanton It didn't work in my specific case, but it lead me to find the problem. I am using the package with Laravel and Laravel's Monolog Json logger is configured not to log the full stack, so in my case i should just find a way to override Monolog's default configuration
